#!/usr/bin/env python3
"""
Consensus Sequence Representativeness Validation Script

This script validates that the consensus sequences generated by the pipeline
adequately represent the original input sequences.

Analysis components:
1. Back-mapping coverage analysis
2. Genotype distribution comparison
3. Similarity distribution statistics
"""

import argparse
import subprocess
import tempfile
import os
import sys
import logging
from collections import Counter, defaultdict
from Bio import SeqIO, AlignIO, pairwise2
from Bio.pairwise2 import format_alignment
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend
import matplotlib.pyplot as plt
import seaborn as sns

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def calculate_similarity(seq1, seq2):
    """
    Calculate pairwise similarity between two sequences.
    Only considers positions where neither sequence has a gap.
    """
    # Align sequences using global alignment
    alignments = pairwise2.align.globalxx(seq1, seq2, one_alignment_only=True)
    if not alignments:
        return 0.0

    aligned_seq1, aligned_seq2, score, begin, end = alignments[0]

    matches = 0
    total = 0

    for a, b in zip(aligned_seq1, aligned_seq2):
        if a != '-' and b != '-':
            total += 1
            if a == b:
                matches += 1

    if total == 0:
        return 0.0

    return (matches / total) * 100


def calculate_similarity_fast(seq1, seq2):
    """
    Fast similarity calculation without alignment.
    Assumes sequences are pre-aligned or similar length.
    """
    # Use the shorter length for comparison
    min_len = min(len(seq1), len(seq2))

    # Count matches at each position
    matches = sum(1 for i in range(min_len) if seq1[i] == seq2[i] and seq1[i] not in ['-', 'N'])

    # Count valid positions (not gaps or N)
    valid_positions = sum(1 for i in range(min_len) if seq1[i] not in ['-', 'N'] and seq2[i] not in ['-', 'N'])

    if valid_positions == 0:
        return 0.0

    return (matches / valid_positions) * 100


def extract_genotype(sequence_id):
    """
    Extract genotype from sequence ID.
    Supports formats like: GII.4_sample_001, GII.4|sample, etc.
    """
    # Remove leading '>'
    if sequence_id.startswith('>'):
        sequence_id = sequence_id[1:]

    # Split by common separators
    for separator in ['_', '|', '.', '-']:
        if separator in sequence_id:
            parts = sequence_id.split(separator)
            # Check if first part looks like a genotype
            if parts[0].upper() in ['GI', 'GII', 'GIII', 'GV', 'GVI']:
                return parts[0]
            # Check for patterns like GII.4
            if '.' in parts[0] and parts[0].upper().startswith('G'):
                return parts[0]

    # If no pattern match, try to find GI/GII pattern in the string
    import re
    match = re.search(r'(G[I|V]{1,2}\.?\d*)', sequence_id, re.IGNORECASE)
    if match:
        return match.group(1).upper()

    return "Unknown"


def run_backmapping_analysis(original_fasta, consensus_fasta, output_prefix, threads=8):
    """
    Perform back-mapping analysis: map each original sequence to its most similar consensus.
    """
    logger.info("Starting back-mapping coverage analysis...")

    # Read sequences
    logger.info(f"Reading original sequences from {original_fasta}")
    original_seqs = list(SeqIO.parse(original_fasta, "fasta"))
    logger.info(f"Loaded {len(original_seqs)} original sequences")

    logger.info(f"Reading consensus sequences from {consensus_fasta}")
    consensus_seqs = list(SeqIO.parse(consensus_fasta, "fasta"))
    logger.info(f"Loaded {len(consensus_seqs)} consensus sequences")

    # For each original sequence, find the most similar consensus
    results = []
    similarities = []

    for i, orig_seq in enumerate(original_seqs):
        if (i + 1) % 100 == 0:
            logger.info(f"Processing original sequence {i+1}/{len(original_seqs)}...")

        orig_seq_str = str(orig_seq.seq).upper()
        best_similarity = 0.0
        best_consensus_id = None

        for cons_seq in consensus_seqs:
            cons_seq_str = str(cons_seq.seq).upper()

            # Use fast similarity calculation
            sim = calculate_similarity_fast(orig_seq_str, cons_seq_str)

            if sim > best_similarity:
                best_similarity = sim
                best_consensus_id = cons_seq.id

        results.append({
            'original_id': orig_seq.id,
            'best_consensus_id': best_consensus_id,
            'similarity': best_similarity,
            'original_genotype': extract_genotype(orig_seq.id),
            'consensus_genotype': extract_genotype(best_consensus_id) if best_consensus_id else "Unknown"
        })
        similarities.append(best_similarity)

    # Calculate statistics
    similarities = np.array(similarities)

    stats = {
        'mean': np.mean(similarities),
        'median': np.median(similarities),
        'std': np.std(similarities),
        'min': np.min(similarities),
        'max': np.max(similarities),
        'percentiles': {
            '5': np.percentile(similarities, 5),
            '10': np.percentile(similarities, 10),
            '25': np.percentile(similarities, 25),
            '75': np.percentile(similarities, 75),
            '90': np.percentile(similarities, 90),
            '95': np.percentile(similarities, 95),
        }
    }

    # Count coverage at different thresholds
    coverage = {
        '>=85%': np.sum(similarities >= 85),
        '>=90%': np.sum(similarities >= 90),
        '>=95%': np.sum(similarities >= 95),
        '>=98%': np.sum(similarities >= 98),
    }

    for threshold, count in coverage.items():
        coverage[threshold] = (count, count / len(similarities) * 100)

    return results, stats, coverage


def analyze_genotype_distribution(original_fasta, consensus_fasta):
    """
    Compare genotype distributions between original and consensus sequences.
    """
    logger.info("Analyzing genotype distributions...")

    # Extract genotypes from original sequences
    original_genotypes = []
    for record in SeqIO.parse(original_fasta, "fasta"):
        gt = extract_genotype(record.id)
        original_genotypes.append(gt)

    # Extract genotypes from consensus sequences
    consensus_genotypes = []
    for record in SeqIO.parse(consensus_fasta, "fasta"):
        gt = extract_genotype(record.id)
        consensus_genotypes.append(gt)

    # Count occurrences
    original_counts = Counter(original_genotypes)
    consensus_counts = Counter(consensus_genotypes)

    # Get all unique genotypes
    all_genotypes = sorted(set(original_counts.keys()) | set(consensus_counts.keys()))

    logger.info(f"Original sequences: {len(original_genotypes)} total, {len(original_counts)} unique genotypes")
    logger.info(f"Consensus sequences: {len(consensus_genotypes)} total, {len(consensus_counts)} unique genotypes")

    return original_counts, consensus_counts, all_genotypes


def generate_report(results, stats, coverage, original_counts, consensus_counts,
                   all_genotypes, original_fasta, consensus_fasta, output_prefix):
    """
    Generate a comprehensive validation report.
    """
    report_file = f"{output_prefix}_validation_report.txt"

    with open(report_file, 'w') as f:
        f.write("=" * 80 + "\n")
        f.write("CONSENSUS SEQUENCE REPRESENTATIVENESS VALIDATION REPORT\n")
        f.write("=" * 80 + "\n\n")

        f.write(f"Original sequences: {original_fasta}\n")
        f.write(f"Consensus sequences: {consensus_fasta}\n\n")

        # Summary statistics
        f.write("1. COVERAGE STATISTICS\n")
        f.write("-" * 80 + "\n")
        f.write(f"Total original sequences: {len(results)}\n")
        f.write(f"Total consensus sequences: {sum(1 for _ in SeqIO.parse(consensus_fasta, 'fasta'))}\n")
        f.write(f"Compression ratio: {len(results) / max(1, sum(1 for _ in SeqIO.parse(consensus_fasta, 'fasta'))):.2f}:1\n\n")

        f.write("Similarity Statistics (each original to its best-matching consensus):\n")
        f.write(f"  Mean:   {stats['mean']:.2f}%\n")
        f.write(f"  Median: {stats['median']:.2f}%\n")
        f.write(f"  Std Dev: {stats['std']:.2f}%\n")
        f.write(f"  Min:    {stats['min']:.2f}%\n")
        f.write(f"  Max:    {stats['max']:.2f}%\n\n")

        f.write("Percentiles:\n")
        for p, val in sorted(stats['percentiles'].items(), key=lambda x: int(x[0])):
            f.write(f"  {p}th percentile: {val:.2f}%\n")
        f.write("\n")

        f.write("Coverage at Different Thresholds:\n")
        for threshold, (count, percentage) in sorted(coverage.items(), key=lambda x: float(x[0].rstrip('%')), reverse=True):
            f.write(f"  Sequences with similarity {threshold}: {count} ({percentage:.2f}%)\n")
        f.write("\n")

        # Genotype comparison
        f.write("2. GENOTYPE DISTRIBUTION COMPARISON\n")
        f.write("-" * 80 + "\n")
        f.write(f"{'Genotype':<15} {'Original Count':<20} {'Consensus Count':<20} {'Status':<15}\n")
        f.write("-" * 80 + "\n")

        for gt in all_genotypes:
            orig_count = original_counts.get(gt, 0)
            cons_count = consensus_counts.get(gt, 0)
            status = "✓ Preserved" if cons_count > 0 else "✗ Lost"

            f.write(f"{gt:<15} {orig_count:<20} {cons_count:<20} {status:<15}\n")

        f.write("\n")

        # Genotypes only in consensus (mixed/new)
        cons_only = set(consensus_counts.keys()) - set(original_counts.keys())
        if cons_only:
            f.write("Genotypes only in consensus (likely mixed/reconstructed):\n")
            for gt in sorted(cons_only):
                f.write(f"  {gt}: {consensus_counts[gt]} sequences\n")
            f.write("\n")

        # Conclusion
        f.write("3. CONCLUSION\n")
        f.write("-" * 80 + "\n")

        high_coverage = coverage['>=90%'][1]
        mean_sim = stats['mean']

        if high_coverage >= 95 and mean_sim >= 90:
            f.write("✓ EXCELLENT: The consensus sequences provide excellent representation.\n")
            f.write(f"  - {high_coverage:.2f}% of original sequences have ≥90% similarity\n")
            f.write(f"  - Mean similarity: {mean_sim:.2f}%\n")
        elif high_coverage >= 85 and mean_sim >= 85:
            f.write("✓ GOOD: The consensus sequences provide good representation.\n")
            f.write(f"  - {high_coverage:.2f}% of original sequences have ≥90% similarity\n")
            f.write(f"  - Mean similarity: {mean_sim:.2f}%\n")
        else:
            f.write("⚠ MODERATE: The consensus sequences show moderate representation.\n")
            f.write(f"  - {high_coverage:.2f}% of original sequences have ≥90% similarity\n")
            f.write(f"  - Mean similarity: {mean_sim:.2f}%\n")
            f.write("  Consider adjusting clustering or consensus parameters.\n")

        f.write("\n")

        # Check for genotype preservation
        preserved_genotypes = sum(1 for gt in original_counts.keys() if gt in consensus_counts and consensus_counts[gt] > 0)
        total_genotypes = len(original_counts)

        if preserved_genotypes == total_genotypes:
            f.write(f"✓ All {total_genotypes} genotypes from original data are preserved.\n")
        else:
            f.write(f"⚠ {preserved_genotypes}/{total_genotypes} genotypes preserved.\n")

    logger.info(f"Validation report written to {report_file}")
    return report_file


def generate_plots(results, stats, output_prefix):
    """
    Generate visualization plots.
    """
    logger.info("Generating visualization plots...")

    similarities = [r['similarity'] for r in results]

    # Create figure with subplots
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    # 1. Similarity distribution histogram
    ax1 = axes[0, 0]
    ax1.hist(similarities, bins=50, color='steelblue', alpha=0.7, edgecolor='black')
    ax1.axvline(stats['mean'], color='red', linestyle='--', linewidth=2, label=f"Mean: {stats['mean']:.2f}%")
    ax1.axvline(stats['median'], color='green', linestyle='--', linewidth=2, label=f"Median: {stats['median']:.2f}%")
    ax1.axvline(90, color='orange', linestyle=':', linewidth=2, label="90% threshold")
    ax1.set_xlabel('Similarity to Best-Matching Consensus (%)', fontsize=11)
    ax1.set_ylabel('Number of Original Sequences', fontsize=11)
    ax1.set_title('Distribution of Similarity Scores', fontsize=13, fontweight='bold')
    ax1.legend()
    ax1.grid(alpha=0.3)

    # 2. Cumulative distribution
    ax2 = axes[0, 1]
    sorted_sim = np.sort(similarities)
    cumulative = np.arange(1, len(sorted_sim) + 1) / len(sorted_sim) * 100
    ax2.plot(sorted_sim, cumulative, color='darkblue', linewidth=2)
    ax2.axhline(95, color='red', linestyle='--', linewidth=1.5, label="95% coverage")
    ax2.axvline(90, color='orange', linestyle='--', linewidth=1.5, label="90% similarity")
    ax2.set_xlabel('Similarity (%)', fontsize=11)
    ax2.set_ylabel('Cumulative Percentage (%)', fontsize=11)
    ax2.set_title('Cumulative Distribution of Similarity', fontsize=13, fontweight='bold')
    ax2.legend()
    ax2.grid(alpha=0.3)

    # 3. Box plot with threshold indicators
    ax3 = axes[1, 0]
    bp = ax3.boxplot([similarities], vert=True, patch_artist=True)
    bp['boxes'][0].set_facecolor('lightblue')
    bp['boxes'][0].set_alpha(0.7)
    ax3.axhline(90, color='orange', linestyle='--', linewidth=2, label="90% threshold")
    ax3.axhline(95, color='red', linestyle='--', linewidth=2, label="95% threshold")
    ax3.set_ylabel('Similarity (%)', fontsize=11)
    ax3.set_title('Box Plot of Similarity Scores', fontsize=13, fontweight='bold')
    ax3.set_xticklabels(['All Sequences'])
    ax3.legend()
    ax3.grid(axis='y', alpha=0.3)

    # 4. Coverage summary bar chart
    ax4 = axes[1, 1]
    thresholds = ['>=85%', '>=90%', '>=95%', '>=98%']
    counts = []
    for t in thresholds:
        count = sum(1 for s in similarities if s >= float(t.rstrip('%')))
        percentage = count / len(similarities) * 100
        counts.append(percentage)

    colors = ['#d7191c', '#fdae61', '#a6d96a', '#1a9641']
    bars = ax4.bar(thresholds, counts, color=colors, alpha=0.7, edgecolor='black')
    ax4.set_ylabel('Percentage of Original Sequences (%)', fontsize=11)
    ax4.set_title('Coverage at Different Similarity Thresholds', fontsize=13, fontweight='bold')
    ax4.set_ylim(0, 105)

    # Add value labels on bars
    for bar, count in zip(bars, counts):
        height = bar.get_height()
        ax4.text(bar.get_x() + bar.get_width()/2., height,
                f'{count:.1f}%', ha='center', va='bottom', fontweight='bold')

    ax4.grid(axis='y', alpha=0.3)

    plt.tight_layout()
    plot_file = f"{output_prefix}_similarity_analysis.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight')
    plt.close()

    logger.info(f"Plot saved to {plot_file}")
    return plot_file


def main():
    parser = argparse.ArgumentParser(
        description="Validate consensus sequence representativeness"
    )
    parser.add_argument("--original", required=True, help="Original input FASTA file")
    parser.add_argument("--consensus", required=True, help="Final consensus FASTA file")
    parser.add_argument("--output_prefix", required=True, help="Output file prefix")
    parser.add_argument("--threads", type=int, default=8, help="Number of threads")
    parser.add_argument("--skip_plots", action="store_true", help="Skip generating plots")

    args = parser.parse_args()

    # Validate input files
    if not os.path.exists(args.original):
        logger.error(f"Original file not found: {args.original}")
        sys.exit(1)

    if not os.path.exists(args.consensus):
        logger.error(f"Consensus file not found: {args.consensus}")
        sys.exit(1)

    logger.info("=" * 80)
    logger.info("CONSENSUS SEQUENCE REPRESENTATIVENESS VALIDATION")
    logger.info("=" * 80)
    logger.info(f"Original sequences: {args.original}")
    logger.info(f"Consensus sequences: {args.consensus}")
    logger.info(f"Output prefix: {args.output_prefix}")

    # Run back-mapping analysis
    results, stats, coverage = run_backmapping_analysis(
        args.original, args.consensus, args.output_prefix, args.threads
    )

    # Analyze genotype distributions
    original_counts, consensus_counts, all_genotypes = analyze_genotype_distribution(
        args.original, args.consensus
    )

    # Generate report
    report_file = generate_report(
        results, stats, coverage, original_counts, consensus_counts,
        all_genotypes, args.original, args.consensus, args.output_prefix
    )

    # Generate plots
    if not args.skip_plots:
        try:
            plot_file = generate_plots(results, stats, args.output_prefix)
        except Exception as e:
            logger.warning(f"Failed to generate plots: {e}")
            logger.info("Continuing without plots...")

    # Print summary
    logger.info("=" * 80)
    logger.info("VALIDATION SUMMARY")
    logger.info("=" * 80)
    logger.info(f"Original sequences: {len(results)}")
    logger.info(f"Mean similarity: {stats['mean']:.2f}%")
    logger.info(f"Median similarity: {stats['median']:.2f}%")
    logger.info(f"Coverage at ≥90% similarity: {coverage['>=90%'][1]:.2f}%")
    logger.info(f"Genotypes preserved: {sum(1 for gt in original_counts.keys() if gt in consensus_counts)}/{len(original_counts)}")
    logger.info("=" * 80)

    logger.info(f"\nReport saved to: {report_file}")


if __name__ == "__main__":
    main()
